splash = false
ipc = true

preload = /home/armand/wallpapers/wallpaper2

wallpaper {
    monitor = eDP-1
    path = /home/armand/wallpapers/wallpaper2
}

wallpaper {
    monitor = DP-6
    path = /home/armand/wallpapers/wallpaper2
}
