splash = false
ipc = true

preload = /home/armand/wallpapers/wallpaper2

# monitor vacio = se aplica a TODOS los monitores (robusto ante cambios de nombre)
wallpaper {
    monitor =
    path = /home/armand/wallpapers/wallpaper2
}
